version: '3'
services:
  postgres:
    image: postgres:15.4
    container_name: fastapi-python-db
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-fastapi-data:/var/lib/postgresql/data
    networks:
      - postgres-fastapi-net

volumes:
  postgres-fastapi-data:

networks:
  postgres-fastapi-net:
    driver: bridge